### ISSUE TITLE
new prerequisite for sendmail

### ISSUE THREAD

**Issue by konstan** [StratusLab/stratuslab.github.com#2]
I noticed a new prerequisite for sendmail.

https://github.com/StratusLab/stratuslab.github.com/blob/master/_posts/2012-09-25-install-cloud-services-installation.md

I remember introducing [messaging] section with smtp_host param that drives this prerequisite. So, by default sendmail should have been installed. If this is not the case - then, either there is a bug or you have something else for smtp_host in your conf.file. Could you please check?

[messaging]
# JSON encoded dictionary with REST endpoints as keys
rest_endpoints = {"http://example.com" : {"username" : "x", "password" : "*"} }
# If set to 'localhost', installation of sendmail package will be done.
# Used with 'email' messaging client, e.g. to send email to a user with detials
# on newly created image.
smtp_host = localhost

**Comment by vangman** [comment]
This is what i have now in stratuslab.cfg

rest_endpoints = {"http://localhost" : {"username" : "foo", "password" : "bar"} }
smtp_host = localhost

Obviously it's the default value. Sendmail package was not installed during status-install and I had to do it by hand. Btw I did one more test with --save and again I didn't get an email notification :-/. I guess it has to do with the rest_endpoints definition which by default are bogus

**Comment by konstan** [comment]
There is obviously a bug in the installation of sendmail. I'll create a ticket for that.

rest_endpoints is for REST messaging and not related to SMTP.

Thanks.
